# Generated by Django 6.0.4 on 2026-04-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('requested_tests', models.TextField(blank=True, null=True)),
                ('summary_for_patient', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consultation_records', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'consultation_records',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=120)),
                ('instructions', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='emr.consultationrecord')),
            ],
            options={
                'db_table': 'prescription_items',
                'indexes': [models.Index(fields=['consultation_record'], name='idx_prescription_consultation')],
            },
        ),
        migrations.CreateModel(
            name='RequestedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tests_normalized', to='emr.consultationrecord')),
            ],
            options={
                'db_table': 'requested_tests',
                'indexes': [models.Index(fields=['consultation_record'], name='idx_req_tests_consult')],
            },
        ),
    ]
