# Generated by Django 6.0.4 on 2026-04-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(default='OD', max_length=50),
        ),
        migrations.AddField(
            model_name='requestedtest',
            name='urgency',
            field=models.CharField(default='routine', max_length=50),
        ),
    ]
