# Generated by Django 6.0.4 on 2026-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('view_analytics', 'Can view analytics dashboard'), ('view_doctor_dashboard', 'Can view doctor dashboard'), ('view_receptionist_dashboard', 'Can view receptionist dashboard'), ('export_data', 'Can export CSV reports')]},
        ),
    ]
