# Generated by Django 6.0.4 on 2026-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # Update existing NULL values to safe defaults before making fields required
        migrations.RunSQL(
            "UPDATE patient_profiles SET address = '' WHERE address IS NULL OR address = '';",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE patient_profiles SET gender = 'Unknown' WHERE gender IS NULL OR gender = '';",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE patient_profiles SET date_of_birth = '1990-01-01' WHERE date_of_birth IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE users SET first_name = '' WHERE first_name IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE users SET last_name = '' WHERE last_name IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE users SET phone = '' WHERE phone IS NULL;",
            migrations.RunSQL.noop,
        ),
        # Now alter fields to remove blank/null
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
