# Generated by Django 6.0.4 on 2026-06-01 14:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_doctorprofile_consultation_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    accounts.models.validate_not_future_date,
                    accounts.models.validate_logical_age,
                ],
            ),
        ),
    ]
