# Generated by Codex on 2026-05-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="appointments",
                to="scheduling.appointmentslot",
            ),
        ),
    ]
