# Generated by Django 6.0.4 on 2026-04-20 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField()),
                ('type', models.CharField(choices=[('DAY_OFF', 'Day Off'), ('VACATION', 'Vacation'), ('SPECIAL_WORKING_DAY', 'Special Working Day')], max_length=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_exceptions', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_schedule_exceptions',
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('generated_from', models.CharField(choices=[('WEEKLY_SCHEDULE', 'Weekly Schedule'), ('EXCEPTION', 'Exception'), ('MANUAL', 'Manual')], default='WEEKLY_SCHEDULE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'appointment_slots',
                'indexes': [models.Index(fields=['doctor', 'slot_date', 'status'], name='idx_slots_doctor_date_status')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'start_datetime', 'end_datetime'), name='uniq_doctor_slot'), models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='chk_slot_time')],
            },
        ),
        migrations.CreateModel(
            name='DoctorWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='accounts.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_weekly_schedules',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'day_of_week', 'start_time', 'end_time'), name='uniq_doctor_weekly_schedule'), models.CheckConstraint(condition=models.Q(('day_of_week__lte', 6)), name='chk_day_of_week'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_schedule_time')],
            },
        ),
    ]
